---
title: "Boyan Exam Exercise"
output: html_notebook
---

# 1. Ice cream

## a)

```{r fig.height=3, fig.width=8}
ice_cream <- read.csv('data/Ice_cream.csv')
ice_cream$ice_cream <- NULL

video.mean <- mean(ice_cream$video)

par(mfrow=c(1,3))
hist(ice_cream$video)
boxplot(ice_cream$video)
qqnorm(ice_cream$video)

shapiro.test(ice_cream$video)
```

```{r}
# Compute 97% CI
video.sd <- sd(ice_cream$video)
margin <- qnorm(0.985)*video.sd/sqrt(length(ice_cream$video))
ci.lower <- video.mean - margin
ci.upper <- video.mean + margin
print(paste("CI:", ci.lower, ci.upper))

# Compute sample size for size 3 CI
margin.target = 3 / 2
n.sample <- (qnorm(0.985)*video.sd/margin.target)^2
print(paste("Required sample size:", ceiling(n.sample)))

# Compute bootstrap CI
B=1000
Tstar=numeric(B)
for (i in 1:B){
  Xstar=sample(ice_cream$video,replace=TRUE)
  Tstar[i]=mean(Xstar)
}
Tstar.015 <- quantile(Tstar, 0.015)
Tstar.985 <- quantile(Tstar, 0.985)
print(paste("Bootstrap CI:", 2*video.mean-Tstar.985, 2*video.mean-Tstar.015))
```

## b)

```{r}
t.test(ice_cream$video, mu=50, alternative = "greater")

t.test(ice_cream$video, mu=51, alternative = "greater")
```

## c)
```{r}
sum.g50 <- sum(ice_cream$video > 50)
binom.test(sum.g50, length(ice_cream$video), p=0.5, alt="g")

wilcox.test(ice_cream$video, mu=50, alt="g")

sum.l42 <- sum(ice_cream$video < 42)
binom.test(sum.l42, length(ice_cream$video), p=0.25, alt="l")
```

## d)
```{r}
# Bootstrap samples
B <- 1000
t <- min(ice_cream$video)
n <- length(ice_cream$video)
ps <- numeric(101)
sd.test <- sqrt(100)
for (j in 0:100){
  tstar <- numeric(B)
  for (i in 1:B){
    xstar <- rnorm(n, mean=j, sd=sd.test)
    tstar[i] <- min(xstar)
  }
  p.left <- sum(tstar<t)/B
  p.right <- sum(tstar>t)/B
  ps[j+1] <- 2*min(p.left, p.right)
}
mus <- seq(0,100)[ps >= 0.05]
print(mus)
```

```{r warning=FALSE}
ps <- numeric(101)
for (j in 0:100){
  ksresult <- ks.test(ice_cream$video, pnorm, j, sd.test)
  ps[j+1] <- ksresult$p.value
}
mus <- seq(0,100)[ps >= 0.05]
print(mus)
```

## e)
```{r}
scores.boys <- ice_cream$video[ice_cream$female==FALSE]
scores.girls <- ice_cream$video[ice_cream$female==TRUE]
par(mfrow=c(1,2))
qqnorm(scores.boys)
qqnorm(scores.girls)

t.test(scores.boys, scores.girls, alt="g")
wilcox.test(scores.boys, scores.girls, alt="g")
ks.test(scores.boys, scores.girls, alternative ="greater")
```

## f)
```{r fig.height=2.5, fig.width=6}
par(mfrow=c(1,3))
qqnorm(ice_cream$video)
shapiro.test(ice_cream$video)
qqnorm(ice_cream$puzzle)
shapiro.test(ice_cream$puzzle)
plot(ice_cream$video, ice_cream$puzzle)
```
```{r}
cor.test(ice_cream$video, ice_cream$puzzle)
cor.test(ice_cream$video, ice_cream$puzzle, method = "spearman")
```

# 2. Sour cream
```{r}
cream <- read.table("data/cream.txt")

```

